In [9]:
#This is the implementation of a classifications algorith using machine learning
#Winsconsin Breast Cancer Classification using Logarithmic Classifications, LinearSVC, Random Forest Classifier
#Using Scikit-learn python 3.7

#importing Data science libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Importing necessary models and datasets from sklearn
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import LinearSVC

#Pointing the model to a variable
cancer = load_breast_cancer()

#Printing the data, description and metrics
print(cancer['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [2]:
cancer.data.shape

(569, 30)

In [3]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

In [7]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [8]:
# Splitting the datasets between training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(cancer.data, cancer.target, random_state= 0)
X_train.shape

(426, 30)

In [10]:
#Calling the logistic regression model 
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
print("Logistic Regression Score ;", logreg.score(X_test, Y_test))

Logistic Regression Score ; 0.951048951048951


C:\Users\charl\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
#Using Cross validation score
cross = cross_val_score(logreg, cancer.data, cancer.target, cv=5)
display(cross)


C:\Users\charl\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\charl\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.93859649, 0.93859649, 0.95614035, 0.9122807 , 0.95575221])

In [13]:
# Making predictions using Random Forest Score 
Rnd = RandomForestClassifier()
Rnd.fit(X_train, Y_train)
print("Random Forest Classification score : ", Rnd.score(X_test, Y_test))

Random Forest Classification score :  0.972027972027972


In [14]:
#Testing result using cross validation score
cross = cross_val_score(Rnd, cancer.data, cancer.target, cv=5)
print(cross)

[0.9122807  0.93859649 0.99122807 0.96491228 0.97345133]


In [15]:
display(cross)

array([0.9122807 , 0.93859649, 0.99122807, 0.96491228, 0.97345133])

In [16]:
#Using Gradient Boost Classifier
GBC = GradientBoostingClassifier()
GBC.fit(X_train, Y_train)
print("Gradient Boost Classifier score:",GBC.score(X_test, Y_test))

Gradient Boost Classifier score: 0.965034965034965


In [18]:
#Cross Validation Score
cross = cross_val_score(GBC, cancer.data, cancer.target, cv=5)
print(cross)

[0.92982456 0.92982456 0.97368421 0.98245614 0.98230088]


In [19]:
#Making Predictions using support vector classifier
lSVC = LinearSVC()
lSVC.fit(X_train, Y_train)
print("Linear support vector classifier :",lSVC.score(X_test, Y_test))

Linear support vector classifier : 0.9440559440559441


C:\Users\charl\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [20]:
#cross validation score
cross = cross_val_score(lSVC, cancer.data, cancer.target, cv=5)
print(cross)

[0.86842105 0.92982456 0.92982456 0.93859649 0.92920354]


C:\Users\charl\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\charl\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\charl\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\charl\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\charl\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations

In [22]:
#Introduction normalization to the datasets
scaler = StandardScaler()
scaler.fit(X_train, Y_train)

#Normalizing X_train and X_test datasets with Standard_scaler
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_test_scaled.shape)
print(X_train_scaled.shape)

(143, 30)
(426, 30)


In [23]:
X_test_scaled

array([[-0.21395901,  0.3125461 , -0.14355187, ...,  1.37043754,
         1.08911166,  1.53928319],
       [-0.26750714,  1.461224  , -0.32955207, ..., -0.84266106,
        -0.71577388, -0.88105993],
       [-0.03922298, -0.86770223, -0.10463112, ..., -0.505318  ,
        -1.20298225, -0.92494342],
       ...,
       [-0.51270124, -1.69096186, -0.54095317, ..., -0.12632201,
         0.33773512, -0.42872244],
       [-0.17732081, -2.01395163, -0.17345939, ..., -0.62875108,
        -0.29500302, -0.65432858],
       [ 1.5305829 , -0.26300709,  1.57961296, ...,  1.6694843 ,
         1.18085869,  0.48889253]])

In [24]:
X_train_scaled

array([[-0.65079907, -0.43057322, -0.68024847, ..., -0.36433881,
         0.32349851, -0.7578486 ],
       [-0.82835341,  0.15226547, -0.82773762, ..., -1.45036679,
         0.62563098, -1.03071387],
       [ 1.68277234,  2.18977235,  1.60009756, ...,  0.72504581,
        -0.51329768, -0.96601386],
       ...,
       [-1.33114223, -0.22172269, -1.3242844 , ..., -0.98806491,
        -0.69995543, -0.12266325],
       [-1.25110186, -0.24600763, -1.28700242, ..., -1.75887319,
        -1.56206114, -1.00989735],
       [-0.74662205,  1.14066273, -0.72203706, ..., -0.2860679 ,
        -1.24094654,  0.2126516 ]])

In [25]:
#Testing Logistic regression model with normalized data

logreg.fit(X_train_scaled, Y_train)
print("Logistic Regression score :", logreg.score(X_test_scaled, Y_test))

Logistic Regression score : 0.958041958041958


In [26]:
#Testing Random Forest Classifier with Standard Scaled data
Rnd.fit(X_train_scaled, Y_train)
print("Random forest classificatuon score : ", Rnd.score(X_test_scaled,Y_test))

Random forest classificatuon score :  0.9790209790209791


In [27]:
#Testing Gradient Boost Classifier
GBC.fit(X_train_scaled, Y_train)
print("Gradient Boost Classifier Score", GBC.score(X_test_scaled, Y_test))

Gradient Boost Classifier Score 0.965034965034965


In [28]:
#Testing linear SVC
lSVC.fit(X_train_scaled, Y_train)
print("Linear Support Vector Classifier :",lSVC.score(X_test_scaled, Y_test))

Linear Support Vector Classifier : 0.9440559440559441
